name: CICD

on:
  pull_request:
  push:
    branches:
      - main
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test Affected Packages
        run: npx nx affected --target tsc,vitest,prettier,eslint,depcheck --base=origin/main --head=${{ github.sha }}

      - name: Build Affected Packages
        if: github.event_name == 'push'
        run: npx nx affected --target build --base=origin/main --head=${{ github.sha }}

      # - name: Publish Affected Packages
      #   if: github.event_name == 'push'
      #   run: npx nx affected --target publish --base=origin/main --head=${{ github.sha }}
